apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: open-liberty
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: open-liberty
    spec:
      containers:
      - image: docker.io/jgawor/getting-started
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 9080
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
